### ISSUE TITLE
非常感謝, 想請問更多細節

### ISSUE THREAD

**Issue by sky790312** [lyrasoft/coding-standards#2]
您好

這篇文章非常實用! 
想請問對於RWD有什麼建議媽
若以bootstrap4為主的size可能會有什麼樣的問題?
還有想知道有關跨國多語系應該要注意到的細節@@
最後
想知道你們撰寫整個網站架構常用的方式(article-content外層)

非常感謝

**Comment by asika32764** [comment]
關於這點，您問的問題實在是大哉問了，較難在這邊探討到，建議可以丟回社群討論。我們的 CSS 編碼標準也可以參考一下
https://github.com/lyrasoft/coding-standards/blob/master/css.md

RWD 下的字體其實沒有太多需要額外處理，還是依照實際看起的狀況修正，通常版面的影響比字體多。

Bootstrap4 因為字體與行距有加大了，需要的修改比較少一些。

跨多語系的話原則以英文為主要排版考量，文件內有一些參考資源有提到中英混和的排版注意事項。
https://goo.gl/1VSzds

網站架構部分可能就是未來有機會寫才會分享囉，不過這些東西大多在網路上比較容易找到資源，搜尋一下應該還是有的

**Comment by sky790312** [comment]
嗯嗯, 感謝回覆
